apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-instance.fullname" . }}
  labels:
    {{- include "k8s-instance.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "k8s-instance.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "k8s-instance.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Chart.Name }}-image-pull-secrets 
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $index, $env := .Values.env }}
            - name: "{{ $env.name }}"
              value: "{{ $env.value }}"
            {{- end }}
          {{- with .Values.container_ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: configmap-env-volume
              mountPath: app/.env
              subPath: .env
          {{- if .Values.container_readinessProbe }}
          {{- if not (empty .Values.container_readinessProbe) }}
          readinessProbe:
            {{- toYaml .Values.container_readinessProbe | nindent 12 }}
          {{- end }}
          {{- end }}

          {{- if .Values.container_livenessProbe }}
          {{- if not (empty .Values.container_livenessProbe) }}
          livenessProbe:
            {{- toYaml .Values.container_livenessProbe | nindent 12 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: configmap-env-volume
        configMap:
          name: {{ .Chart.Name }}-configmap-env
          items:
            - key: .env
              path: .env
