apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-appsettings-secrets
type: Opaque
data:
  .env: |-
    {{- range $key, $value := .Values.secretData }}
    {{ $key }}={{ $value }}
    {{- end }}
