apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-appsettings-secrets
type: Opaque
data:
  .env: |-
    {{- $env := (tpl (include "envConfig" .) . | b64enc) }}
    {{- printf "%s" $env }}
