branch: true
ignore-not-existing: true
llvm: true
output-path: ./lcov.info
output-type: lcov
# filter: covered
# prefix-dir: /home/user/build/

ignore:
  - "/*"
#   - "C:/*"
#   - "../*"
path-mapping: []
#   - "/path1"
#   - "/path2"
