//! `SeaORM` entity-level active enums. Originally generated by
//! `sea-orm-codegen` 0.12.15 against the `m20240409_151952_release_100`
//! migration. Physically moved from
//! `application_core/src/entities/sea_orm_active_enums.rs` per the
//! `consolidate-category-ai-translate-into-domain-posts` change. Regenerate
//! against the `domain_posts` migration set if the schema ever changes.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "category_type")]
pub enum CategoryType {
    #[sea_orm(string_value = "Blog")]
    Blog,
    #[sea_orm(string_value = "Other")]
    Other,
}
