name: Automation Test my-cms-api

# TEMPORARY DISABLED, PLEASE CHECK BACK LATER
# on:
#   pull_request:
#     branches: ["main"]
#   workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

# Please run test in folder apps/api from repository
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          default: true
          components: 'llvm-tools-preview'
      - uses: SierraSoftworks/setup-grcov@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: latest 
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features --no-fail-fast --manifest-path apps/api/Cargo.toml # Customize args for your own needs
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Cinstrument-coverage -Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
          LLVM_PROFILE_FILE: "test-llvm-reports/my-cms-%p-%m.profraw"
      # Take Coverage Reports
      - name: Run Coverage Report with grcov
        run: grcov . --binary-path apps/api/target/debug/deps/ -s apps/api -t lcov --ignore-not-existing --ignore '../**' --ignore '/*' -o ./lcov.info
      # Upload Coverage Reports to Third Party
      - name: Upload coverage reports to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info 
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
