name: build and test cms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test  -- -Z unstable-options --format json --report-time | tee results.json
    - name: JUnit Report Action
      uses: mikepenz/action-junit-report@v4.3.1

    - uses: mikepenz/action-junit-report@main
      with:
        check_name: Test Report
        fail_on_failure: true
        require_tests: true
        summary: ${{ steps.cargo_reporter.outputs.summary }}
