//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod category;
pub mod post;

#[cfg(test)]
mod tests {
    #[async_std::test]
    async fn handle_create_post_testcase_01() {
        let var_name = assert!(true);
    }
}
